package org.scoula.consumption.domain;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ExpectedSpendingVO {
    private Long expectedNo;

    private Integer memberNo;

    private Long categoryNo;
    private String categoryName;

    private Long expectedAmount;

    private String merchant;
    private String memo;

    private LocalDate expectedDate;

    private boolean autoGenerated;
}
