#jdbc.driver=com.mysql.cj.jdbc.Driver
#jdbc.url=jdbc:mysql://127.0.0.1:3306/scoula_db
jdbc.driver=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
jdbc.url=jdbc:log4jdbc:mysql://localhost:3306/youthtapa
jdbc.username=root
jdbc.password=1234
youthcenter.api.url=https://www.youthcenter.go.kr/go/ythip/getPlcy
youthcenter.api.key=${YOUTH_CENTER_API_KEY}
jwt.secret=${JWT_SECRET}
redis.host=localhost
redis.port=6379