package org.scoula.consumption.service;

import lombok.RequiredArgsConstructor;
import org.scoula.consumption.domain.ExpectedSpendingVO;
import org.scoula.consumption.domain.SpendingVO;
import org.scoula.consumption.dto.*;
import org.scoula.consumption.mapper.ConsumptionMapper;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.time.YearMonth;
import java.util.*;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class ConsumptionServiceImpl implements ConsumptionService {

    // 정기적 예상 소비로 인정하려면 같은 소비처로 최근 몇 달 연속 소비 내역이 있어야 하는지
    private static final int REQUIRED_MONTHS = 2;

    private final ConsumptionMapper consumptionMapper;

    @Override
    public ConsumptionCalendarDTO getCal(Integer memberNo, String yearMonth) {

        // 달력을 조회할 때마다 예정일이 지난 예상 소비 삭제
        consumptionMapper.replaceExpected();

        // 정기 지출 자동 감지
        try {
            detectRecurringSpending(memberNo);
        } catch (Exception e) {
            System.out.println("정기 지출 감지 중 에러 발생: " + e.getMessage());
            e.printStackTrace();
        }

        // 1. DB에서 이번 달 소비 내역 / 예상 소비 목록 조회
        List<SpendingVO> spendings =
                consumptionMapper.selectSpendingByMonth(memberNo, yearMonth);

        List<ExpectedSpendingVO> expectedList =
                consumptionMapper.selectExpectedByMonth(memberNo, yearMonth);

        System.out.println("=================");
        System.out.println(expectedList);
        System.out.println("=================");

        // 2. 총 지출 / 예상 소비 합계 계산
        long totalSpend = spendings.stream()
                .mapToLong(SpendingVO::getAmount)
                .sum();

        long expectedTotal = expectedList.stream()
                .mapToLong(ExpectedSpendingVO::getExpectedAmount)
                .sum();

        // 3. 카테고리 list
        List<CategoryDTO> categorySummary = new ArrayList<>();

        for (SpendingVO spendingVO : spendings) {
            CategoryDTO categoryDTO = CategoryDTO.builder()
                    .categoryName(spendingVO.getCategoryName())
                    .categoryNo(spendingVO.getCategoryNo())
                    .build();
            categorySummary.add(categoryDTO);
        }

        // 4. 날짜별 소비 내역 / 예상 소비 그룹화
        Map<String, List<SpendingVO>> spendingsByDate =
                spendings.stream()
                        .collect(Collectors.groupingBy(
                                v -> v.getSpendingDate().toString()
                        ));

        Map<String, List<ExpectedSpendingVO>> expectedByDate =
                expectedList.stream()
                        .collect(Collectors.groupingBy(
                                v -> v.getExpectedDate().toString()
                        ));

        Set<String> allDates = new TreeSet<>();
        allDates.addAll(spendingsByDate.keySet());
        allDates.addAll(expectedByDate.keySet());

        List<DayDTO> days = new ArrayList<>();

        for (String date : allDates) {

            List<SpendingItemDTO> spendingItems = new ArrayList<>();

            for (SpendingVO v : spendingsByDate.getOrDefault(date, List.of())) {
                SpendingItemDTO item = SpendingItemDTO.builder()
                        .spendingNo(v.getSpendingNo())
                        .categoryName(v.getCategoryName())
                        .amount(v.getAmount())
                        .merchant(v.getMerchant())
                        .payMethod(v.getPayMethod())
                        .memo(v.getMemo())
                        .build();
                spendingItems.add(item);
            }

            List<ExpectedItemDTO> expectedItems = new ArrayList<>();

            for (ExpectedSpendingVO v : expectedByDate.getOrDefault(date, List.of())) {
                ExpectedItemDTO item = ExpectedItemDTO.builder()
                        .expectedNo(v.getExpectedNo())
                        .categoryNo(v.getCategoryNo())
                        .categoryName(v.getCategoryName())
                        .amount(v.getExpectedAmount())
                        .merchant(v.getMerchant())
                        .memo(v.getMemo())
                        .autoGenerated(v.isAutoGenerated())
                        .build();
                expectedItems.add(item);
            }

            DayDTO dayDto = DayDTO.builder()
                    .date(date)
                    .spendings(spendingItems)
                    .expectedSpendings(expectedItems)
                    .build();
            days.add(dayDto);
        }

        // 5. 최종 응답 DTO 생성
        return ConsumptionCalendarDTO.builder()
                .yearMonth(yearMonth)
                .totalSpend(totalSpend)
                .expectedTotal(expectedTotal)
                .category(categorySummary)
                .days(days)
                .build();
    }

    // 예상 소비 추가
    @Override
    public void addExpected(Integer memberNo, ExpectedReqDTO request) {
        ExpectedSpendingVO vo = new ExpectedSpendingVO();
        vo.setMemberNo(memberNo);
        vo.setCategoryNo(request.getCategoryNo());
        vo.setExpectedAmount(request.getExpectedAmount());
        vo.setExpectedDate(LocalDate.parse(request.getExpectedDate()));
        vo.setMerchant(request.getMerchant());
        vo.setMemo(request.getMemo());

        consumptionMapper.insertExpected(vo);
    }

    // 예상 소비 수정
    @Override
    public void updateExpected(Long expectedNo, ExpectedReqDTO request) {
        ExpectedSpendingVO vo = new ExpectedSpendingVO();
        vo.setExpectedNo(expectedNo);
        vo.setCategoryNo(request.getCategoryNo());
        vo.setExpectedAmount(request.getExpectedAmount());
        vo.setExpectedDate(LocalDate.parse(request.getExpectedDate()));
        vo.setMerchant(request.getMerchant());
        vo.setMemo(request.getMemo());

        consumptionMapper.updateExpected(vo);
    }

    // 예상 소비 삭제
    @Override
    public void deleteExpected(Long expectedNo) {
        consumptionMapper.deleteExpected(expectedNo);
    }

    // 정기적 예상 소비 감지하여 자동 등록
    @Override
    public void detectRecurringSpending(Integer memberNo) {
        // 소비처가 있는 최근 소비 내역들을 가져 온다
        List<SpendingVO> recentSpending = consumptionMapper.selectRecentSpendingWithMerchant(memberNo);

        // 소비처 + 카테고리 번호가 같은 내역들끼리 묶는다
        Map<String, List<SpendingVO>> grouped = recentSpending.stream()
                .collect(Collectors.groupingBy(v -> v.getMerchant() + "|" + v.getCategoryNo() + "|" + v.getSpendingDate().getDayOfMonth()));

        YearMonth thisMonth = YearMonth.now();
        YearMonth lastMonth = thisMonth.minusMonths(1);

        for (List<SpendingVO> sameGroupList : grouped.values()) {
            try {
                processGroup(memberNo, sameGroupList, thisMonth, lastMonth);
            } catch (Exception e) {
                System.out.println("정기 지출 감지 중 한 그룹 처리 실패: " + e.getMessage());
            }
        }
    }

    // 소비처 + 카테고리가 같은 그룹 하나를 보고, 정기 지출이면 예상 소비로 등록
    private void processGroup(Integer memberNo, List<SpendingVO> sameGroupList, YearMonth thisMonth, YearMonth lastMonth) {
        // 지난달에 있었던 것들 중 가장 최근 걸 기준(=예측의 기준)으로 삼는다
        SpendingVO latest = sameGroupList.stream()
                .filter(v -> YearMonth.from(v.getSpendingDate()).equals(lastMonth))
                .max(Comparator.comparing(SpendingVO::getSpendingDate))
                .orElse(null);

        if (latest == null) {
            return; // 지난 달에 없었으면 정기적 소비 내역 후보가 아니다
        }

        // 이전 달들에도 금액이 같고 날짜도 같은 내역이 있었는지 확인
        if (!hasSameSpendingInEarlierMonths(sameGroupList, thisMonth, latest)) {
            return;
        }

        // 이번 달에도 지난 달이랑 같은 날짜에 결제될 것이라고 예측
        int dayOfMonth = latest.getSpendingDate().getDayOfMonth();
        LocalDate predictedDate = predictNextDate(thisMonth, dayOfMonth);

        if (predictedDate.isBefore(LocalDate.now())) {
            predictedDate = predictNextDate(thisMonth.plusMonths(1), dayOfMonth);
        }

        // 이미 그 날짜로 등록된 예상 소비가 있으면 생성 안 함
        ExpectedSpendingVO checkCondition = new ExpectedSpendingVO();
        checkCondition.setMemberNo(memberNo);
        checkCondition.setMerchant(latest.getMerchant());
        checkCondition.setCategoryNo(latest.getCategoryNo());
        checkCondition.setExpectedDate(predictedDate);

        if (consumptionMapper.countExpectedByCondition(checkCondition) > 0) {
            return;
        }

        // 새 예상 소비로 등록
        ExpectedSpendingVO newExpected = new ExpectedSpendingVO();
        newExpected.setMemberNo(memberNo);
        newExpected.setCategoryNo(latest.getCategoryNo());
        newExpected.setExpectedAmount(latest.getAmount());
        newExpected.setExpectedDate(predictedDate);
        newExpected.setMerchant(latest.getMerchant());
        newExpected.setAutoGenerated(true);

        consumptionMapper.insertExpected(newExpected);
    }

    private boolean hasSameSpendingInEarlierMonths(List<SpendingVO> list, YearMonth thisMonth, SpendingVO reference) {
        for (int i = 2; i <= REQUIRED_MONTHS; i++) {
            YearMonth targetMonth = thisMonth.minusMonths(i);

            boolean hasSameSpending = list.stream()
                    .anyMatch(v ->
                            YearMonth.from(v.getSpendingDate()).equals(targetMonth)
                                    && v.getAmount().equals(reference.getAmount())
                                    && v.getSpendingDate().getDayOfMonth() == reference.getSpendingDate().getDayOfMonth()
                    );

            if (!hasSameSpending) {
                return false;
            }
        }
        return true;
    }

    private LocalDate predictNextDate(YearMonth month, int dayOfMonth) {
        int lastDayOfMonth = month.lengthOfMonth();
        int safeDay = Math.min(dayOfMonth, lastDayOfMonth);
        return month.atDay(safeDay);
    }
}